package com.padcx.shared.utils

const val ROOT_CHECKOUT = "checkout"
const val ROOT_CONSULT_REQUEST = "consult_request"
const val ROOT_CONSULTATION = "consultation"
const val ROOT_DOCTORS = "doctors"
const val ROOT_PATIENTS = "patient"
const val ROOT_QUESTIONS = "questions"
const val ROOT_SPECIALITY = "speciality"
const val CHILD_PATIENT = "patient"
const val CHILD_PRESCRIPTION = "prescription"
const val CHILD_ADDRESS = "address"
const val CHILD_GENERAL_QUESTIONS = "general_questions"
const val CHILD_RECENT_DOCTORS = "recent_doctors"
const val CHILD_CASE_SUMMARY = "case_summary"
const val CHILD_CONSULTEES = "consultees"
const val CHILD_DOCTOR = "doctor"
const val CHILD_MESSAGES = "messages"
const val CHILD_MEDICINE = "medicine"
const val CHILD_QUESTIONS = "questions"